### PR TITLE
style.css - rockodiles

### PR DESCRIPTION
**Pull request by rishabhnat08**

### CODE REVIEW

**Comment by A3PK** [comment]
Please submit all your code in ONE pull request.

**Comment by rishabhnat08** [comment]
> Please submit all your code in ONE pull request.

I don't understand how to submit it in one

**Comment by A3PK** [comment]
After placing ALL your code within the repository, create a pull request across forks. We understand that this may be time-consuming, but approving, merging, and cleaning several pull requests is also extremely difficult when other teams also need their requests approved.

**Comment by A3PK** [comment]
To save time, all three prs are being merged; but please do not submit individual files as such again.

**Pull request merged**
